apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-persistence
  name: session-persistence
  namespace: session-persistence
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: session-persistence
  type: ClusterIP
